version: '3.8'

services:
  coffee-rnb-ui:
    container_name: coffee-rnb-ui
    build:
      context: .
      dockerfile: ./apps/ui/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
