version: '3.8'

services:
  super-duper-spoon-web:
    container_name: super-duper-spoon-web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    ports:
      - "4132:4132"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
